### ISSUE TITLE
CSS heart beating animation

### ISSUE THREAD

**Issue by shreyanshp25** [pranjay-poddar/Dev-Geeks#75] opened 2021-10-22 19:41 UTC
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by GundaSudarrshan** [comment] 2022-07-14 11:56
@pranjay-poddar  Pls assign me this issue I wanted to work on this

**Comment by pavankumarraju13** [comment] 2022-07-14 12:01
@pranjay-poddar plz assign me this issue  i like to work

**Comment by GundaSudarrshan** [comment] 2022-07-15 15:33
@pranjay-poddar  thanks for assigning me this issue , I wanted to ask that if this issue is labelled to HSCO and level of the Issue is mentioned or not

**Comment by GundaSudarrshan** [comment] 2022-07-16 06:21
@pranjay-poddar  thanks for the PR, I think we can **Close this Issue** for Better Workflow of the Repository as the **PR is merged**
What do you think!!!!!

**Closed** 2022-07-16 12:33 UTC
Labels: HSOC22, CSS3, Animation-CSS, front-end, HSOC22-Level-1
